version: '3'
services:
  appdb:
    image: postgres
    container_name: "db_container"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/initdb:/docker-entrypoint-initdb.d
      - ./postgres/db_data:/var/lib/postgresql/data/

  flask:
    build:
      context: .
      dockerfile: Dockerfile_flask
    command: python app.py
    container_name: flask_container
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"

  vue:
    build:
      context: .
      dockerfile: Dockerfile_vue
    command: npm run serve
    image: vue_img
    container_name: vue_container
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
