version: '3'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile_python
    command: pipenv run start
    container_name: flask_container
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
  vue:
    build:
      context: .
      dockerfile: Dockerfile_node
    # command: npm run dev
    image: vue_img
    container_name: vue_container
    tty: true
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
